// Generates app/src/generated/prompts.ts from the canonical agent prompts in agents/
// and the shared knowledge base in knowledge/.
//
// The app is not allowed to hold its own copy of the science. The markdown files in
// agents/ and knowledge/ remain the single source of truth; this script bakes them
// into the bundle at build time so the deployed site runs the same prompts a
// scientist would paste into an LLM by hand.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "app/src/generated/prompts.ts");

const read = (p) => readFileSync(join(ROOT, p), "utf8");
const maybe = (p) => {
  try {
    return read(p);
  } catch {
    return "";
  }
};

const AGENTS = [
  { id: "01", slug: "target-id", title: "Target Identification", dir: "agents/01-target-id" },
  { id: "02", slug: "target-validation", title: "Target Validation", dir: "agents/02-target-validation" },
  { id: "03", slug: "bispecific-design", title: "Bispecific Design", dir: "agents/03-bispecific-design" },
  { id: "04", slug: "spr-binding", title: "SPR / Biochemical Binding", dir: "agents/04-spr-binding" },
  { id: "05", slug: "cell-functional", title: "Cell-Based Functional", dir: "agents/05-cell-functional" },
  { id: "06", slug: "in-vivo", title: "In Vivo & Clinical", dir: "agents/06-in-vivo" },
  { id: "07", slug: "experimental-data", title: "Experimental Data Ingestion", dir: "agents/07-experimental-data" },
];

const agents = AGENTS.map((a) => ({
  ...a,
  prompt: read(`${a.dir}/prompt.md`),
  background: maybe(`${a.dir}/background.md`),
  refinement: maybe(`${a.dir}/refinement-prompt.md`),
}));

const knowledge = {
  glossary: read("knowledge/glossary.md"),
  databases: read("knowledge/public-databases.md"),
};

const orchestrator = read("orchestrator/prompt.md");

const banner = `// AUTO-GENERATED by scripts/gen-prompts.mjs — do not edit by hand.
// Source of truth: agents/**/prompt.md, agents/**/background.md, knowledge/*.md
// Regenerate with: node scripts/gen-prompts.mjs
`;

const body = `${banner}
export interface AgentSpec {
  id: string;
  slug: string;
  title: string;
  prompt: string;
  background: string;
  refinement: string;
}

export const AGENTS: AgentSpec[] = ${JSON.stringify(agents.map(({ dir, ...rest }) => rest), null, 2)};

export const KNOWLEDGE = ${JSON.stringify(knowledge, null, 2)};

export const ORCHESTRATOR = ${JSON.stringify(orchestrator)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);

const bytes = Buffer.byteLength(body);
console.log(`gen-prompts: wrote ${OUT} (${agents.length} agents, ${(bytes / 1024).toFixed(1)} KB)`);
